version: '3.8'

services:
  nginx:
    image: nginx:latest
    ports:
      - "8080:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./nginx/entrypoint.sh:/etc/nginx/entrypoint.sh:ro
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
    depends_on:
      - app_blue
      - app_green
    environment:
      - ACTIVE_POOL=${ACTIVE_POOL}
      - PORT=${PORT}
    command: ["/bin/bash", "-c", "/etc/nginx/entrypoint.sh && nginx -g 'daemon off;'"]

  app_blue:
    image: ${BLUE_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_BLUE}
      - PORT=${PORT}
    ports:
      - "8081:${PORT}"

  app_green:
    image: ${GREEN_IMAGE}
    environment:
      - RELEASE_ID=${RELEASE_ID_GREEN}
      - PORT=${PORT}
    ports:
      - "8082:${PORT}"