FROM nginx:latest
COPY nginx.conf /etc/nginx/nginx.conf
COPY blue.conf /etc/nginx/conf.d/blue.conf
COPY green.conf /etc/nginx/conf.d/green.conf
COPY backup.conf /etc/nginx/conf.d/backup.conf
EXPOSE 80